#!/usr/bin/env python3
"""Render deterministic Markdown projections from canonical family YAML."""
from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]


def load_yaml(relative_path: str) -> dict[str, Any]:
    with (ROOT / relative_path).open(encoding="utf-8") as handle:
        value = yaml.safe_load(handle)
    if not isinstance(value, dict):
        raise ValueError(f"{relative_path} must contain a YAML mapping")
    return value


def cell(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, list):
        value = ", ".join(str(item) for item in value)
    return " ".join(str(value).split()).replace("|", "\\|")


def render_decisions() -> str:
    decisions = load_yaml("design/decisions.yaml").get("decisions", [])
    counts = Counter(item["status"] for item in decisions)
    lines = [
        "# Family Decisions",
        "",
        "**Authority:** Governance index  ",
        "**Detailed source:** `design/decision-ledger.md`  ",
        "**Machine-readable source:** `design/decisions.yaml`",
        "",
        "<!-- Generated by scripts/render-projections.py; edit design/decisions.yaml. -->",
        "",
        "## Counts",
        "",
    ]
    for status in sorted(counts):
        lines.append(f"- **{status}:** {counts[status]}")
    lines.extend([
        "",
        "## Decision index",
        "",
        "| ID | Status | Title | Decision |",
        "| --- | --- | --- | --- |",
    ])
    for item in decisions:
        lines.append(
            f"| {cell(item['id'])} | {cell(item['status'])} | "
            f"{cell(item['title'])} | {cell(item['decision'])} |"
        )
    return "\n".join(lines) + "\n"


def render_matrix() -> str:
    source = load_yaml("spec/capability-family-matrix.yaml")
    family_id = source["family_id"]
    lines = [
        "# Capability Family Matrix",
        "",
        "**Authority:** Family capability-depth and project-seed index  ",
        "**Machine-readable source:** `capability-family-matrix.yaml`  ",
        f"**Family ID:** `{family_id}`",
        "",
        "<!-- Generated by scripts/render-projections.py; edit capability-family-matrix.yaml. -->",
        "",
        "This matrix is not a yes/no support table. It records purpose, authority posture, execution depth, result type, relationships, exact repository identity, and current project status.",
        "",
        "| ID | Product | Character | Repository | Governing question | Provisional class | Project execution | Network | Result | Primary skill | Creation order | Status |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for item in source.get("capabilities", []):
        classes = [entry["value"] for entry in item.get("capability_classes", [])]
        skills = item.get("primary_agent_skills", [])
        repository = item["repository"]["name"]
        lines.append(
            f"| {cell(item['id'])} | {cell(item['product_name'])} | "
            f"**{cell(item['canonical_character_identity'])}** | `{cell(repository)}` | "
            f"{cell(item['governing_question'])} | {cell(classes)} | "
            f"{cell(item['project_execution'])} | {cell(item['network'])} | "
            f"{cell(item['durable_result_type'])} | {cell(skills[0] if skills else '')} | "
            f"{cell(item['creation_priority'])} | {cell(item['status'])} |"
        )
    lines.extend([
        "",
        "## Interpretation rules",
        "",
        "- `ESTABLISHED REFERENCE IMPLEMENTATION` means the UCA build packet is mature enough to govern project creation, not that the engine is already implemented.",
        "- `PROJECT SEED` means this packet supplies authoritative generation context, while capability-specific research and build-packet generation remain future work.",
        "- character identities, the family namespace, and repository mappings are established; capability classes and CLI/package/image/schema/skill/protocol names remain provisional or separately undecided.",
        "- no matrix relationship grants authority or mandates technical runtime coupling.",
    ])
    return "\n".join(lines) + "\n"


def render_relationship_graph() -> str:
    source = load_yaml("architecture/capability-relationship-graph.yaml")
    nodes = source.get("nodes", [])
    aliases = {item["id"]: f"C{index}" for index, item in enumerate(nodes, 1)}
    lines = [
        "# Capability Relationship Graph",
        "",
        "**Authority:** Family relationship model  ",
        "**Status:** `ACCEPTED` relationships; most are optional evidence or aggregation, not runtime dependencies  ",
        "**Machine-readable source:** `capability-relationship-graph.yaml`",
        "",
        "<!-- Generated by scripts/render-projections.py; edit capability-relationship-graph.yaml. -->",
        "",
        "```mermaid",
        "flowchart LR",
    ]
    for item in nodes:
        lines.append(
            f"    {aliases[item['id']]}[{cell(item['canonical_character_identity'])}<br/>{cell(item['name'])}]"
        )
    lines.append("")
    for edge in source.get("edges", []):
        label = cell(edge["type"].replace("_", " "))
        lines.append(f"    {aliases[edge['from']]} -. {label} .-> {aliases[edge['to']]}")
    lines.extend([
        "```",
        "",
        "| From | To | Relationship | Meaning |",
        "| --- | --- | --- | --- |",
    ])
    for edge in source.get("edges", []):
        lines.append(
            f"| {cell(edge['from'])} | {cell(edge['to'])} | {cell(edge['type'])} | {cell(edge['meaning'])} |"
        )
    lines.extend(["", "## Constraints", ""])
    for constraint in source.get("constraints", []):
        lines.append(f"- {cell(constraint)}")
    return "\n".join(lines) + "\n"


def render_dependency_graph() -> str:
    source = load_yaml("architecture/project-seed-dependency-graph.yaml")
    nodes = {item["id"]: item for item in source.get("nodes", [])}
    lines = [
        "# Project Seed and Creation Dependency Graph",
        "",
        "**Status:** `ACCEPTED` strategic sequence; not a mandatory technical dependency graph  ",
        "**Machine-readable source:** `project-seed-dependency-graph.yaml`",
        "",
        "<!-- Generated by scripts/render-projections.py; edit project-seed-dependency-graph.yaml. -->",
        "",
        "## Capability sequence",
        "",
        "| Order | Capability ID | Character | Repository | Status |",
        "| --- | --- | --- | --- | --- |",
    ]
    for capability_id in source.get("recommended_sequence", []):
        item = nodes[capability_id]
        lines.append(
            f"| {cell(item['creation_priority'])} | {cell(capability_id)} | "
            f"**{cell(item['canonical_character_identity'])}** | `{cell(item['repository'])}` | {cell(item['status'])} |"
        )
    lines.extend([
        "",
        "## Learning milestones",
        "",
        "| ID | Milestone |",
        "| --- | --- |",
    ])
    for milestone in source.get("milestones", []):
        lines.append(f"| {cell(milestone['id'])} | {cell(milestone['name'])} |")
    lines.extend(["", "## Sequence constraints", ""])
    for note in source.get("notes", []):
        lines.append(f"- {cell(note)}")
    return "\n".join(lines) + "\n"


def render_workstreams() -> str:
    workstreams = load_yaml("agent/family-workstreams.yaml").get("workstreams", [])
    lines = [
        "# Family Workstreams",
        "",
        "**Machine-readable source:** `family-workstreams.yaml`",
        "",
        "<!-- Generated by scripts/render-projections.py; edit family-workstreams.yaml. -->",
        "",
        "| ID | Workstream | Objective |",
        "| --- | --- | --- |",
    ]
    for item in workstreams:
        lines.append(f"| {cell(item['id'])} | {cell(item['name'])} | {cell(item['objective'])} |")
    lines.extend([
        "",
        "## Coordination rule",
        "",
        "Workstreams may proceed in parallel when they do not redefine shared semantics. Contract changes synchronize through FW-01/FW-02/FW-06. Capability-specific seed improvements should not be copied across all capabilities until the shared need is demonstrated.",
    ])
    return "\n".join(lines) + "\n"


def projections() -> dict[str, str]:
    return {
        "DECISIONS.md": render_decisions(),
        "agent/family-workstreams.md": render_workstreams(),
        "architecture/capability-relationship-graph.md": render_relationship_graph(),
        "architecture/project-seed-dependency-graph.md": render_dependency_graph(),
        "spec/capability-family-matrix.md": render_matrix(),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()

    drift: list[str] = []
    for relative_path, expected in projections().items():
        path = ROOT / relative_path
        actual = path.read_text(encoding="utf-8") if path.is_file() else None
        if actual == expected:
            continue
        drift.append(relative_path)
        if args.write:
            path.write_text(expected, encoding="utf-8")

    if drift and args.check:
        for relative_path in drift:
            print(f"projection drift: {relative_path}", file=sys.stderr)
        return 1
    if args.write:
        print(f"rendered {len(drift)} changed projection(s)")
    else:
        print("all deterministic projections are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
